### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KenticoCloudDeliveryJavaRxSDK#19]
- [ ] Set up CI using Travis
  - a build should be created when a commit is merged to master and when a PR is submitted
  - here's the project: https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/
- [ ] [Protect the master branch](https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/settings/branches/master)
- [ ] Add a badge to README
- [ ] Add a sample unit test
- [ ] Run the tests as a part of the build

Resources:
- https://docs.travis-ci.com/user/languages/android/
- https://github.com/andrewhr/rxjava-android-example/blob/master/.travis.yml

**Comment by Enngage** [comment]
@kentico-timothyf , could you please take a look at this?

**Comment by Enngage** [comment]
Can we make this a higher priority and fix the CI to pass?

**Comment by petrsvihlik** [comment]
@Enngage do you have capacity to work on this yourself (or perhaps @kentico-timothyf)?

Otherwise, I'll ask @Simply007 to do it.

**Comment by Enngage** [comment]
@petrsvihlik Not at the moment unfortunately.

**Comment by petrsvihlik** [comment]
thanks @kentico-timothyf! let's track progress during our community sync meetings. please let me know if anything changes regarding your capacity.

**Comment by cunhazera** [comment]
@petrsvihlik is anyone taking care of it?
If not, you can assign this issue to me.

**Comment by petrsvihlik** [comment]
hi @cunhazera, it would be awesome if you could help us with this one.

please accept the [invitation](https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/invitations) I've just sent you. You'll then have access to the Travis configuration. plus, I'll be able to assign this issue to you.

**Comment by cunhazera** [comment]
@petrsvihlik it's done.

**Comment by petrsvihlik** [comment]
can you verify that you can access and modify the project in travis? https://travis-ci.org/Kentico/KenticoCloudDeliveryJavaRxSDK/

**Comment by cunhazera** [comment]
Checked, that's all ok. I'll work on this ASAP
