### ISSUE TITLE
Make sure community profile is  all green

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KenticoCloudDeliveryJavaRxSDK#22]
- [x] Has Description
- [x] Has README
- [x] Has Code of Conduct (#24)
- [x] Has Contributing (#23)
- [x] Has License
- [x] Has Issue or pull request template (#25)

**Comment by petrsvihlik** [comment]
We'll take care of issue/pr templates separately. We need to set them up for all our repos.

reference: https://kentico.atlassian.net/browse/DC-399
