### ISSUE TITLE
Issue or pull request templates

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/KenticoCloudDeliveryJavaRxSDK#25]
See https://help.github.com/articles/creating-an-issue-template-for-your-repository/ and https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ for details.

**Comment by petrsvihlik** [comment]
We'll take care of issue/pr templates separately. We need to set them up for all our repos.

reference: https://kentico.atlassian.net/browse/DC-399
