### ISSUE TITLE
Document publishing process

### ISSUE THREAD

**Issue by Enngage** [Kentico/KenticoCloudDeliveryJavaRxSDK#27]
We need some guidelines as how to publish new versions to jcenter/maven. This should ideally by part of main readme or separate page here on github (depending on how difficult/long the process is)

**Comment by Enngage** [comment]
@kentico-timothyf , can you please document the above so that we can start releasing updates effectively?

**Comment by petrsvihlik** [comment]
@Enngage could you please check with @kentico-timothyf what the status is? thx

**Comment by petrsvihlik** [comment]
https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/blob/master/RELEASE.md
