### ISSUE TITLE
Solve package deployment issues

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KenticoCloudDeliveryJavaRxSDK#30]
- [x] Maven Central Package is 2.0.0 X jCenter Package is 2.0.1 - shouldn't they be in sync?
- [x] packages on jCenter are published under `kentico-timothyf` - we should create an official kentico (kenticocloud) account that we'll all have access to (sorry if this wasn't clear from the beginning)
- [x] update badges in readme

**Comment by Enngage** [comment]
Any updates on this?
