### ISSUE TITLE
Create README, CONTRIBUTING, etc.

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KenticoCloudDeliveryJavaRxSDK#7]
Similarly to other delivery SDKs, the README file should contain:

- [x] download & installation instructions (maven, gradle...)
- [x] simple usage (instantiation of the client and retrieval of content items)
- [x] sample app link
  - https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/tree/master/sample-android-app
  - https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/tree/master/sample-java-app
- [x] info for contributors (link to CONTRIBUTING)

please refer to the https://kentico.atlassian.net/wiki/spaces/KID/pages/217294130/Requirements+for+an+OS+project checklist

**Comment by Enngage** [comment]
Okey, it is now public :-) 

@kentico-timothyf , it would be great if you could come up with some article/steps about the process of publishing new versions and include it here (main or separate readme) on github. I expect that I will be doing some changes and would potentially want to publish them.

**Comment by petrsvihlik** [comment]
@Enngage you can create a separate task for Tim.

**Comment by petrsvihlik** [comment]
done
