### ISSUE TITLE
Update the official documentation

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/KenticoCloudDeliveryJavaRxSDK#8]
- update the feature matrix https://developer.kenticocloud.com/docs/delivery-sdks
- add code examples to the API reference https://developer.kenticocloud.com/reference
  - https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/tree/master/delivery-tests/src/test/java/com/kenticocloud/delivery/tests/official
- add [sample apps](https://developer.kenticocloud.com/docs/sample-applications)
  - https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/tree/master/sample-android-app
  - https://github.com/Kentico/KenticoCloudDeliveryJavaRxSDK/tree/master/sample-java-app

You can write the examples and submit them to CTC backlog (https://kentico.atlassian.net/browse/CTC). Our TWs will process them.

**Comment by JanLenoch** [comment]
Internal reference for feature matrix: https://kentico.atlassian.net/browse/CTC-162

**Comment by JanLenoch** [comment]
@Enngage , could you pls review the code examples that I've added to the [Tutorials section](https://developer.kenticocloud.com/v1/docs)? Thanks!
